spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batchdemo?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      platform: mysql # schema-@@platform@@.sql 이라는 SQL 스크립트 실행 목적
    job:
      #name: ${job.name} # Job 이름을 외부에서 동적으로 지정
      enabled: false # Spring Boot 실행 시, 자동으로 Job을 실행할지를 결정

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info